plugins {
    id("java")
}

group = "io.yoy"
version = "1.0-SNAPSHOT"

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21);
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

dependencies {
    implementation 'net.datafaker:datafaker:2.2.2'
    implementation("io.github.cdimascio:java-dotenv:5.2.2")
    implementation 'org.assertj:assertj-core:3.27.7'
    implementation("io.cucumber:cucumber-java:7.18.1")
    implementation("com.microsoft.playwright:playwright:1.62.0")
    testImplementation(platform("org.junit:junit-bom:5.10.0"))
    testImplementation("org.junit.jupiter:junit-jupiter")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
    implementation("com.codeborne:selenide:7.17.0")
    implementation("org.seleniumhq.selenium:selenium-java:4.46.0")
    testImplementation("org.slf4j:slf4j-simple:2.0.13")
    implementation 'org.apache.poi:poi-ooxml:5.2.5'
    compileOnly("org.projectlombok:lombok:1.18.46")
    annotationProcessor("org.projectlombok:lombok:1.18.46")

    testCompileOnly("org.projectlombok:lombok:1.18.46")
    testAnnotationProcessor("org.projectlombok:lombok:1.18.46")
}

tasks.test {
    useJUnitPlatform()
}